checking if usecli environment variable is set
microsoft/terraform-provider-power-platform pull request #336
Opened 2024-06-12 15:46 UTC by polatengin

To be able to remove hard-coded `use_cli = {true, false}` config from provider section, provider should be able to determine if a specific environment variable is set.

Before;

```terraform
provider "powerplatform" {
  use_cli = true
}
```

After _(with POWER_PLATFORM_USE_CLI environment variable is set)_;

```terraform
provider "powerplatform" {
}
```

closes #334

2024-06-12 16:04 UTC, eduardodfmex approved these changes

2024-06-12 16:05 UTC, ianjensenisme commented
Why does the environment config trump the provider config? This is more of a "food for thought" question, as I've also added variable handling that uses this priority order, so not worth changing, but I wonder if we've gotten it backwards throughout the provider. I'm probably just not thinking of an obvious reason to do things in that priority order. Anywho, LGTM.

2024-06-12 16:05 UTC, ianjensenisme submitted a review, later dismissed
Why does the environment config trump the provider config? This is more of a "food for thought" question, as I've also added variable handling that uses this priority order, so not worth changing, but I wonder if we've gotten it backwards throughout the provider. I'm probably just not thinking of an obvious reason to do things in that priority order. Anywho, LGTM.

2024-06-12 16:45 UTC, mattdot requested changes

2024-06-12 16:45 UTC, mattdot commented on internal/powerplatform/provider.go
> +	}
```suggestion
	_, envUseCli := os.LookupEnv("POWER_PLATFORM_USE_CLI")
	if config.UseCli.IsNull() {
		useCli = envUseCli
	} else {
		useCli = config.UseCli.ValueBool()
	}
```

2024-06-12 17:58 UTC, polatengin commented on internal/powerplatform/provider.go
> +	}
fair 👍 made the changes..

2024-06-13 07:17 UTC, mawasile approved these changes

2024-06-13 17:10 UTC, eduardodfmex approved these changes

2024-06-13 17:49 UTC, mattdot approved these changes

2024-06-13 17:49 UTC, merged